FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY backend/package.json backend/pnpm-lock.yaml* backend/.npmrc* ./

RUN pnpm install --shamefully-hoist

COPY backend/ .

EXPOSE 4000
CMD ["pnpm", "run", "dev"]