networks:
  app_network:

services:
  mongo:
    image: mongo:8
    container_name: mongo_db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    ports:
      - "27017:27017"   # opcional para host
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  backend:
    build: 
      context: ../
      dockerfile: backend/Dockerfile.dev
    container_name: backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ../backend:/app:cached      # sincroniza código host ↔ contenedor
      - /app/node_modules    # evita sobrescribir node_modules del contenedor
    environment:
      NODE_ENV: development
      MONGO_URI: ${MONGO_URI}
      TEST_MP_ACCESS_TOKEN: ${TEST_MP_ACCESS_TOKEN}
      TEST_MP_PUBLIC_KEY: ${TEST_MP_PUBLIC_KEY}
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      S3_INTERNAL_ENDPOINT: ${S3_INTERNAL_ENDPOINT}
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT}
      VITE_API_URL: ${VITE_API_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    depends_on:
      - mongo
    networks:
      - app_network

  frontend:
    build: 
      context: ../
      dockerfile: frontend/Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173" # puerto por defecto de Vite
    volumes:
      - ../frontend:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
      VITE_API_URL: ${VITE_API_URL}   # para que el front se conecte al back
    depends_on:
      - backend
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Consola Web
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app_network

volumes:
  mongo_data:
  minio_data:
