networks:
  app_network:

services:
  mongo:
    image: mongo:8
    container_name: mongo_db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    ports:
      - "27017:27017"   # opcional para host
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  backend:
    build: 
      context: ../
      dockerfile: backend/Dockerfile.dev
    container_name: backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ../backend:/app:cached      # sincroniza código host ↔ contenedor
      - /app/node_modules    # evita sobrescribir node_modules del contenedor
    environment:
      NODE_ENV: development
      MONGO_URI: ${MONGO_URI}
      TEST_MP_ACCESS_TOKEN: ${TEST_MP_ACCESS_TOKEN}
      TEST_MP_PUBLIC_KEY: ${TEST_MP_PUBLIC_KEY}
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      S3_INTERNAL_ENDPOINT: ${S3_INTERNAL_ENDPOINT}
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - mongo
      - redis
    networks:
      - app_network

  frontend:
    build: 
      context: ../
      dockerfile: frontend/Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000" # puerto por defecto de Next.js
    volumes:
      - ../frontend:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}   # para que el front se conecte al back
      NEXT_PUBLIC_INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    depends_on:
      - backend
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Consola Web
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  minio_data:
  redis_data:
