networks:
  test_network:

services:
  test_db:
    image: mongo:8
    container_name: storehub-db-test
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    networks:
      - test_network

  test_minio:
    image: minio/minio
    container_name: storehub-minio-test
    environment:
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: testpassword
    command: server /data
    networks:
      - test_network

  api-tests:
    build: 
      context: ../
      dockerfile: backend/Dockerfile.dev
    container_name: storehub-api-tests
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: test
      MONGO_URI: mongodb://test_db:27017/platform_meta_test
      S3_INTERNAL_ENDPOINT: http://test_minio:9000
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: testpassword
      JWT_SECRET: test_secret_key_123
      PORT: 4000
      NEXT_PUBLIC_INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    depends_on:
      - test_db
      - test_minio
    networks:
      - test_network
    command: npm test 

  frontend-tests:
    build: 
      context: ../
      dockerfile: frontend/Dockerfile.dev
    container_name: storehub-front-tests
    environment:
      NODE_ENV: test
      NEXT_PUBLIC_API_URL: http://api-tests:4000
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - test_network
    command: pnpm test